### ISSUE TITLE
this package has incorrect peer dependency

### ISSUE THREAD

**Issue by Coyas** [joe-bell/next-google-fonts#112]
**Describe the bug**
when trying to install "yarn add next-google-fonts" i get this warning
> warning " > next-google-fonts@2.1.0" has incorrect peer dependency "next@>= 10.0.7"

**To Reproduce**
yarn add next-google-fonts
Is there a way to fix it?

**Comment by joe-bell** [comment]
Yep! Just install `next` v10.0.7 or higher
