### ISSUE TITLE
New version prevents multiple `<GoogleFonts>` tags

### ISSUE THREAD

**Issue by mikestopcontinues** [joe-bell/next-google-fonts#118]
**Describe the bug**

Since the update to `2.2.0`, I can no longer inject multiple `<GoogleFonts>` tags. This breaks my font-selection widget. Version `2.1.0` works, so it looks like the new keys designed to prevent duplicates are to blame.

I see why the key attributes are a good idea, but I think they need to be based on (a) the href being requested or (b) a key chosen by the end-user.

Here's my full use-case:
1. User selects their font category
2. A selector widget populates with examples of the font they chose and makes individual `<GoogleFonts>` tags for all of the fonts in that category. I request them separately because it makes it appear faster to the user
3. The user cycles through choices
4. Whichever font is currently selected, I download the complete set so they can see a live preview of the font on their website.
5. They can change category or click save.

All this to say, I make a lot of font requests. 

**Expected behavior**

So, my inclination would be to support the (a) and (b) cases above. I think most users would assume you can use the component multiple times.

Thanks!

**Comment by joe-bell** [comment]
Hello! The `<GoogleFonts>` tag prevents duplicates for a good reason - it's not supported.

A single tag ensures that fonts are loaded in the [fastest](https://github.com/joe-bell/next-google-fonts#how-does-this-compare-to-nextjs-font-optimization) way. If you want to use multiple fonts, I'd suggest [chaining fonts in your `href`](https://developers.google.com/fonts/docs/css2#multiple_families) (in your case defined in the cycle state).

**Comment by mikestopcontinues** [comment]
Hey, loading all the fonts for the picker together would not be faster for the user. With just ten groups of ten fonts, the user would have to wait for 10x payload before the picker does anything at all. I actually simplified my actual use case for this example, which are bundles of three fonts (logo, head, body with multiple font variants for each). And though the head and body fonts repeat a bit, loading them all up front is slow.

The other thing. Even if I were to use this method, I would still need two font tags, one for the fonts I use in the editor app, and one that I only need on the page with the font picker. 

I also can't subset the fonts with the single tag method you suggest, as you can only subset either all fonts you request or none of them. The user should only have to download the full font bundle for those they want to preview.

I understand this isn't the most common use-case, but it can't be that uncommon, can it? It seems like the only alternative is to store page-specific logic in _app to handle which page uses which fonts, but that muddies the separation of concerns completely.
