### ISSUE TITLE
How to Use on All Pages

### ISSUE THREAD

**Issue by thecodeclimber** [joe-bell/next-google-fonts#43]
If I want to add a font to all pages on my site, I am wondering the recommended way of doing this?  Via the `_document.js` file?  On my main layout file?  My `pages/index.js` file?  Something else?

I'm not 100% clear how to do this properly.

**Comment by joe-bell** [comment]
Hey @thecodeclimber, you've got the right idea! I would advise creating something like a Layout component and using that for all your pages.

Alternatively you can try Lee Robinson's approach which also works just as fine:
https://github.com/leerob/leerob.io/blob/master/pages/_document.js#L9

Let me know how you get on?

**Comment by joe-bell** [comment]
@thecodeclimber how did you get on?

Another approach would be to follow the README example which adds a custom `Head` component. This could be utilised in a `Layout` component or included in each page

**Comment by joe-bell** [comment]
Closing as solutions have been offered and this issue seems to be inactive
