### ISSUE TITLE
Not working on Safari

### ISSUE THREAD

**Issue by cgcullen** [joe-bell/next-google-fonts#44]
This works great on Chrome, but it's not loading the font for Safari.
Is there something I need to add to make safari work?

**Comment by joe-bell** [comment]
Hey @cgcullen! I can't seem to identify the Google Fonts links in your `<head>`. 

Have you imported the `GoogleFonts` component? Have you made sure to add some custom CSS to define the font-family?

If you're still stuck after retracing the [README](https://github.com/joe-bell/next-google-fonts#setup), could you setup a CodeSandbox/GitHub for me to look at? I'd be more than happy to help you figure it out

**Comment by cgcullen** [comment]
Thanks @joe-bell!  I finally figured it out.  I have the GoogleFonts in my _document.js file.  I moved it to my _app.js file and it worked.  I'm using Tailwindcss, so not sure if that has something to do with it too.

**Comment by joe-bell** [comment]
OK so for Tailwind I think you'll want something like this!

1. `tailwind.config.js`
   ```js
    module.exports = {
      theme: {
        fontFamily: {
          // Check the Google Fonts usage guide to figure out what name you should
          // use in your CSS
          body: ['your-body-google-font', 'sans-serif'],
        },
        // Rest of your theme
      }
    }
   ```
2. `_document.js`
   ```jsx
    import Document, { Html, Head, Main, NextScript } from "next/document";
    import React from "react";
    import GoogleFonts from "next-google-fonts";

    class MyDocument extends Document {
      render() {
        return (
          <Html lang="en">
            <GoogleFonts href="your-google-font-href" />
            <Head>
              {/* Any additional head tags you have like title, description etc. */}
            </Head>
            {/* `font-body` is a class generated by the above Tailwind config */}
            <body className="font-body">
              <Main />
              <NextScript />
            </body>
          </Html>
        );
      }
    }

    export default MyDocument;
   ```

I think that should do the trick? But again it's difficult for me to guess without seeing the code! Let me know how you get on

**Comment by cgcullen** [comment]
This is what I have in the tailwind.config.js for fontFamily:

```
    fontFamily: {
      "open-sans": ['"Open Sans"'],
      poppins: ["'Poppins'", "'sans-serif'"],
      sans: [
        '"Open Sans"',
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        '"Segoe UI"',
        "Roboto",
        '"Helvetica Neue"',
        "Arial",
        '"Noto Sans"',
        "sans-serif",
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],

```
I had what you have in _document.js, however that wasn't working in Safari.  I moved the import for <GoogleFonts and the component to my app.js and it now works in Safari as well as Chrome.

_app.js

```
import GoogleFonts from "next-google-fonts"

export default function App({ Component, pageProps }) {
  return (
    <Fragment>
      <GoogleFonts href="https://fonts.googleapis.com/css?family=Poppins&display=swap" />
      <GoogleFonts href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" />
      <Head>
...

```
This is a complex site and uses Apollo Client and many other packages, so there could be a conflict somewhere?  At any rate, it appears to be working now that it's in the _app.js instead of _document.js.

Thanks for your help!

**Comment by joe-bell** [comment]
Ah! I think the problem here is that you're bringing in `GoogleFonts` twice rather than making it a [single request](https://developers.google.com/fonts/docs/getting_started#specifying_font_families_and_styles_in_a_stylesheet_url).

Try this instead:

```diff
+<GoogleFonts href="https://fonts.googleapis.com/css?family=Poppins|Open+Sans&display=swap" />
-<GoogleFonts href="https://fonts.googleapis.com/css?family=Poppins&display=swap" />
-<GoogleFonts href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" />
```

**Comment by cgcullen** [comment]
That didn't work :(. It works either way in the _apps.js, but neither works in the _document.js file.

**Comment by joe-bell** [comment]
Strange, I really don't know - it's difficult to determine without a reproduction. Either way I'm glad you got it fixed!
