### ISSUE TITLE
Guidance on using this alongside vanilla `next/head` 

### ISSUE THREAD

**Issue by dalanmiller** [joe-bell/next-google-fonts#47]
If I'm customizing my main document structure via providing `_document.tsx`, could you provide guidance on how to use `next-google-fonts` with the vanilla `Head` component? 

Would it be like so? As this does not appear to work for me. 

```
render() {
    return (
      <Html lang="en">
        <React.Fragment>
          <Head />
          <GoogleFonts href="https://fonts.googleapis.com/..."/>
        </React.Fragment>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
```

**Comment by joe-bell** [comment]
Hey @dalanmiller, the issue you're having here is that you're mixing up `Head` from `next/document` and `next/head`.

From [Next.js's "Custom Document" docs](https://nextjs.org/docs/advanced-features/custom-document):
>The `<Head />` component used here is not the same one from next/head. The `<Head />` component used here should only be used for any `<head>` code that is common for all pages. For all other cases, such as `<title>` tags, we recommend using `next/head` in your pages or components.

So there are two routes you can take here:
1. Follow the steps outlined in the [README](https://github.com/joe-bell/next-google-fonts#setup) and create a custom `Head` component which you can re-use in each page or a shared layout.
2. Place the GoogleFonts component inside `next/document`'s `Head`
    ```diff
    render() {
        return (
          <Html lang="en">
    -       <React.Fragment>
    -         <Head />
    +       <Head>
              <GoogleFonts href="https://fonts.googleapis.com/..."/>
    +       </Head>
    -       </React.Fragment>
            <body>
              <Main />
              <NextScript />
            </body>
          </Html>
        )
      }
    }
    ```

and finally don't forget to add your CSS! Hope that helps 😊

**Comment by dalanmiller** [comment]
Derp, thanks for the kind and careful explanation @joe-bell. 

I didn't see this as an explicit option and got wary that having the GoogleFonts component inside the Head component was incorrect from the warning. And again thinking next/head and next/document were the same.

Will give this a go!

**Comment by joe-bell** [comment]
Nice one, keep me posted!

**Comment by joe-bell** [comment]
@dalanmiller how did you get on?

**Comment by joe-bell** [comment]
I've updated the README with a new `Document` example which I _hope_ answers your question

Feel free to re-open if you're still hitting issues!

**Comment by joe-bell** [comment]
I've updated the README with a new `Document` example which I _hope_ answers your question

Feel free to re-open if you're still hitting issues!
