### ISSUE TITLE
Head (`next/document`) not support passing NextHead (`next/head`) as a child.

### ISSUE THREAD

**Issue by fky2015** [joe-bell/next-google-fonts#57]
**Describe the bug**
As coded, the `GoogleFonts` should be expanded as `<NextHead> <link ... /> </NextHead>`.
And the `Head` component (next/document) only accept what directly in `<header />`, such as `<link />`.
So the example you wrote in `README.md` seems not working anymore. (seen as below)

https://github.com/joe-bell/next-google-fonts/blob/f1edfede90ad605027b3530c36da616a6ad97a57/README.md#L37-L58

**To Reproduce**

1. Follow the instruction in `README.md`

**Expected behavior**
Several `<link>` related to async loading fonts were expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/16451516/95613061-eea38c80-0a96-11eb-9f1c-124cb245fa5c.png)

I try to use both `<GoogleFonts />` and `<link />` in `<Head />`, as you can see, only `<link />` was dealing with properly.

**Desktop (please complete the following information):**

- OS: Arch Linux x86_64 5.8.12-arch1-1
- Browser Chromium
- Version 85.0.4183.121

**Additional context**
I think Remove outside `<Head>` in the component is just ok. (And of course, docs should also be updated)

**Comment by joe-bell** [comment]
Cheers for the report @fky2015, I'll take a look into this next week 🙂 

Can I ask what versions of Next and next-google-fonts you're using?

**Comment by omarkhatibgg** [comment]
It does not work any more

**Comment by fky2015** [comment]
> Can I ask what versions of Next and next-google-fonts you're using?

```
next@9.5.4
next-google-fonts@1.2.1
```

Sorry for the delayed response.

**Comment by joe-bell** [comment]
Thanks @fky2015, looks like you're right - the suggested `_document.jsx` approach isn't working for next@9.5.4 and I have no idea why…

I'll take your recommendation and revert the docs to how it was originally (creating a custom component).

Really appreciate you alerting me about this

**Comment by joe-bell** [comment]
I've [updated the `README`](https://github.com/joe-bell/next-google-fonts/commit/049abaf52444a42f324d9f2e8cfe6cfba6c4852b) so I'll close this for now. If more people report this as an issue then I'll raise one with Next.js

Thanks again @fky2015!
