### ISSUE TITLE
why not useLayoutEffect hook ?

### ISSUE THREAD

**Issue by EminQasimov** [joe-bell/next-google-fonts#93]
I think using useLayoutEffect will be better.
``` 
const useIsomorphicLayoutEffect =  typeof window !== 'undefined' ? useLayoutEffect : useEffect;

useIsomorphicLayoutEffect (() => {
    if (!hydratedRef.current) {
      hydrated = true;
      hydratedRef.current = true;
      rerender(true);
    }
}, []);
```

**Comment by joe-bell** [comment]
Why? Need a bit more of a justification here rather than just an opinion ([see the issue template](https://github.com/joe-bell/next-google-fonts/blob/main/.github/ISSUE_TEMPLATE/feature_request.md))
